name: Build and run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang, MSVC]
        exclude:
          - os: ubuntu-latest
            compiler: MSVC
          - os: windows-latest
            compiler: gcc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Linux environment
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Set up Windows + MSVC environment
        if: matrix.os == 'windows-latest' && matrix.compiler == 'MSVC'
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
          choco install visualstudio2019-workload-vctools

      - name: Set up Windows + Clang environment
        if: matrix.os == 'windows-latest' && matrix.compiler == 'clang'
        run: |
          choco install llvm
          refreshenv

      - name: Configure CMake
        run: cmake -DCMAKE_COMPILER_CXX=CXX=${{ matrix.compiler }} -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        if: matrix.os == 'ubuntu-latest'
        run: ./build/tests/run_tests

      - name: Run tests
        if: matrix.os == 'windows-latest'
        run: .\build\tests\run_tests.exe
