name: Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        compiler: [clang, MSVC]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ninja for clang
        if: matrix.compiler == 'clang'
        run: choco install ninja -y

      - name: Configure CMake for clang
        if: matrix.compiler == 'clang'
        run: |
          $args = (
            "-G Ninja",
            "-S .",
            "-B build",
            "--config Release")
          $args = $args -join ' '
          Invoke-Expression "cmake $args"

      - name: Configure CMake for MSVC
        if: matrix.compiler == 'MSVC'
        run: cmake -S . -B build --config Release

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          & ".\build\tests\run_tests.exe"
