name: Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        compiler: [clang, MSVC]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ninja for clang
        if: matrix.compiler == 'clang'
        run: choco install ninja -y

      - name: Configure CMake for clang
        if: matrix.compiler == 'clang'
        run: |
          $args = (
            "-DCMAKE_BUILD_TYPE=`"Release`"",
            "-DCMAKE_C_COMPILER=`"C:\Program Files\LLVM\bin\clang.exe`"",
            "-DCMAKE_CXX_COMPILER=`"C:\Program Files\LLVM\bin\clang++.exe`"",
            "-G Ninja",
            "-S .",
            "-B build")
          $args = $args -join ' '
          cmake $args

      - name: Configure CMake for MSVC
        if: matrix.compiler == 'MSVC'
        run: cmake -DCMAKE_BUILD_TYPE="Release" -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: .\build\tests\run_tests.exe
